# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"-\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\rHelloResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"G\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nimage_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"I\n\rImageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x0fprocessing_time\x18\x03 \x01(\x01\x32\x8a\x01\n\x0e\x45xampleService\x12\x39\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponse\x12=\n\x0cProcessImage\x12\x15.example.ImageRequest\x1a\x16.example.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=71
  _globals['_HELLORESPONSE']._serialized_start=73
  _globals['_HELLORESPONSE']._serialized_end=122
  _globals['_IMAGEREQUEST']._serialized_start=124
  _globals['_IMAGEREQUEST']._serialized_end=195
  _globals['_IMAGERESPONSE']._serialized_start=197
  _globals['_IMAGERESPONSE']._serialized_end=270
  _globals['_EXAMPLESERVICE']._serialized_start=273
  _globals['_EXAMPLESERVICE']._serialized_end=411
# @@protoc_insertion_point(module_scope)
